### ISSUE TITLE
线上环境无法正常使用

### ISSUE THREAD

**Issue by lenkyes** [mongkok/fastapi-debug-toolbar#9]
你好，同样一套代码我在本地使用没有问题，线上环境就无法正常使用了，直接位置跑到了左下了，而且无法加载出来。
[本地正常图：](https://tvax2.sinaimg.cn/large/008lNUu9gy1gytely1y5vj30zj0o6wm8.jpg)
[线上无法使用图：](https://tva3.sinaimg.cn/large/008lNUu9gy1gytep47jfyj30if0lbn07.jpg)

**Comment by mongkok** [comment]
Hey @lenkyes , this package uses the `Request.url_for` method to generate absolute URLs (not relative URLs).

As I see your issue seems to be related to the static files, use uvicorn `--proxy-headers` option as described here https://github.com/encode/starlette/issues/538#issuecomment-518748568.

It may be useful to add a new settings related to this:

```py
from debug_toolbar.middleware import DebugToolbarMiddleware
from fastapi import FastAPI

app = FastAPI(debug=True)

app.add_middleware(
    DebugToolbarMiddleware,
    # request.url_for by default
    url_for=lambda request: request.app.url_path_for,
)
```

.. so we can easily select between absolute or relative urls.
